// Builds the journey viewer into one IIFE script and one stylesheet that
// render_map.py inlines, so the rendered map stays a single offline file.
//
// Also writes THIRD_PARTY_NOTICES.txt from the packages that actually ended up
// in the bundle, and puts a short attribution banner at the top of the script
// so the notice travels inside every rendered page.
//
//   npm run build            writes to plugins/aipos/skills/aipos-map-render/scripts/assets
//   JOURNEY_VIEWER_OUT=dir   writes somewhere else (used by the CI freshness check)
import { build } from "esbuild";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = process.env.JOURNEY_VIEWER_OUT
  || resolve(here, "../../plugins/aipos/skills/aipos-map-render/scripts/assets");
mkdirSync(out, { recursive: true });

const options = {
  entryPoints: { "journey-viewer": resolve(here, "src/main.jsx") },
  outdir: out,
  bundle: true,
  minify: true,
  format: "iife",
  target: ["es2020"],
  jsx: "automatic",
  legalComments: "none",
  define: { "process.env.NODE_ENV": '"production"' },
  logLevel: "info",
};

// First pass: find out which packages the bundle contains.
const probe = await build({ ...options, write: false, metafile: true, logLevel: "silent" });
const packages = new Map();
for (const input of Object.keys(probe.metafile.inputs)) {
  const m = input.match(/node_modules\/((?:@[^/]+\/)?[^/]+)\//);
  if (!m || packages.has(m[1])) continue;
  const dir = join(here, "node_modules", m[1]);
  const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  const licenseFile = readdirSync(dir).find((f) => /^licen[cs]e(\.|$)/i.test(f));
  const text = licenseFile ? readFileSync(join(dir, licenseFile), "utf8").trim() : null;
  if (!text) throw new Error(`${m[1]} ships no licence file; add its notice by hand before bundling it`);
  const copyright = text.split("\n").map((l) => l.trim()).filter((l) => /^copyright\b/i.test(l));
  packages.set(m[1], { name: pkg.name, version: pkg.version, license: pkg.license, text, copyright });
}
const sorted = [...packages.values()].sort((a, b) => a.name.localeCompare(b.name));

const banner = [
  "/*! aipos journey viewer. Bundles third-party code under permissive licences;",
  " * full texts in THIRD_PARTY_NOTICES.txt beside this file in aipos-map-render/scripts/assets.",
  ...sorted.map((p) => ` * ${p.name}@${p.version} (${p.license})${p.copyright.length ? ` ${p.copyright.join("; ").replace(/\*\//g, "* /")}` : ""}`),
  " */",
].join("\n");

await build({ ...options, banner: { js: banner } });

const notices = [
  "Third-party software bundled into journey-viewer.js",
  "",
  "Generated by viewers/journey/build.mjs from the packages in the bundle. Do not edit.",
  "",
  ...sorted.flatMap((p) => [
    "=".repeat(78),
    `${p.name} ${p.version} — ${p.license}`,
    "=".repeat(78),
    "",
    p.text,
    "",
  ]),
].join("\n");
writeFileSync(join(out, "THIRD_PARTY_NOTICES.txt"), notices);
console.log(`  ${join(out, "THIRD_PARTY_NOTICES.txt")}  ${sorted.length} packages`);

if (!existsSync(join(out, "journey-viewer.js"))) throw new Error("bundle was not written");
